### ISSUE TITLE
用什么工具抓包的，在返回登录状态的那一条怎么抓不到啊

### ISSUE THREAD

**Issue by elsonwx** [J3n5en/the-115-api#2]
`url = 'http://im37.115.com/chat/r'
        params = {
            'VER':'2',
            'c':'b0',
            's':session_id,
            '_t':str(int(time.time()*1000)),
        }`

这个抓包看不到返回结果啊，好奇怪

**Comment by J3n5en** [comment]
我直接用chrome的调试工具，

**Comment by elsonwx** [comment]
现在这个long polling好像返回的response body都是空格，现在115在前端是怎么区分登录状态的，有研究过吗
